/**
 * js/exercises/arpeggi.js
 * Contiene dati per esercizi sugli arpeggi.
 * **VERSIONE SUPER AMPLIATA E CORRETTA**
 */

const arpeggiExercises = [

    // === Sezione 1: Arpeggi Triadi Maggiori (Asc/Desc - 1 Ottava) ===
    { id: "arp-cmaj-triad-1oct", name: "Arp C Maggiore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ],
        notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["c/3"], duration: "q", midiValue: 48 } ]},
    { id: "arp-gmaj-triad-1oct", name: "Arp G Maggiore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "G", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["g/4"], duration: "q", midiValue: 67 } ],
        notesBass: [ { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["g/3"], duration: "q", midiValue: 55 } ]},
    { id: "arp-dmaj-triad-1oct", name: "Arp D Maggiore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "D", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["f#/4"], duration: "8", midiValue: 66 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["f#/4"], duration: "8", midiValue: 66 }, { keys: ["d/4"], duration: "q", midiValue: 62 } ],
        notesBass: [ { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["f#/3"], duration: "8", midiValue: 54 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["f#/3"], duration: "8", midiValue: 54 }, { keys: ["d/3"], duration: "q", midiValue: 50 } ]},
    { id: "arp-amaj-triad-1oct", name: "Arp A Maggiore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "A", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c#/5"], duration: "8", midiValue: 73 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["a/5"], duration: "8", midiValue: 81 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["c#/5"], duration: "8", midiValue: 73 }, { keys: ["a/4"], duration: "q", midiValue: 69 } ],
        notesBass: [ { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["c#/4"], duration: "8", midiValue: 61 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c#/4"], duration: "8", midiValue: 61 }, { keys: ["a/3"], duration: "q", midiValue: 57 } ]},
    { id: "arp-emaj-triad-1oct", name: "Arp E Maggiore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "E", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g#/4"], duration: "8", midiValue: 68 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["g#/4"], duration: "8", midiValue: 68 }, { keys: ["e/4"], duration: "q", midiValue: 64 } ],
        notesBass: [ { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g#/3"], duration: "8", midiValue: 56 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["g#/3"], duration: "8", midiValue: 56 }, { keys: ["e/3"], duration: "q", midiValue: 52 } ]},
    { id: "arp-fmaj-triad-1oct", name: "Arp F Maggiore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "F", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["f/5"], duration: "8", midiValue: 77 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["f/4"], duration: "q", midiValue: 65 } ],
        notesBass: [ { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["f/3"], duration: "q", midiValue: 53 } ]},
    { id: "arp-bbmaj-triad-1oct", name: "Arp Bb Maggiore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "Bb", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["bb/3"], duration: "8", midiValue: 58 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["bb/4"], duration: "8", midiValue: 70 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["bb/3"], duration: "q", midiValue: 58 } ],
        notesBass: [ { keys: ["bb/2"], duration: "8", midiValue: 46 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["bb/3"], duration: "8", midiValue: 58 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["bb/2"], duration: "q", midiValue: 46 } ]},

    // === Sezione 2: Arpeggi Triadi Minori (Asc/Desc - 1 Ottava) ===
    { id: "arp-amin-triad-1oct", name: "Arp A Minore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "Am", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["a/5"], duration: "8", midiValue: 81 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["a/4"], duration: "q", midiValue: 69 } ],
        notesBass: [ { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["a/3"], duration: "q", midiValue: 57 } ]},
    { id: "arp-emin-triad-1oct", name: "Arp E Minore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "Em", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["e/4"], duration: "q", midiValue: 64 } ],
        notesBass: [ { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["e/3"], duration: "q", midiValue: 52 } ]},
    { id: "arp-dmin-triad-1oct", name: "Arp D Minore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "Dm", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["d/4"], duration: "q", midiValue: 62 } ],
        notesBass: [ { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["d/3"], duration: "q", midiValue: 50 } ]},
    { id: "arp-gmin-triad-1oct", name: "Arp G Minore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "Gm", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["bb/4"], duration: "8", midiValue: 70 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["bb/4"], duration: "8", midiValue: 70 }, { keys: ["g/4"], duration: "q", midiValue: 67 } ],
        notesBass: [ { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["bb/3"], duration: "8", midiValue: 58 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["bb/3"], duration: "8", midiValue: 58 }, { keys: ["g/3"], duration: "q", midiValue: 55 } ]},
    { id: "arp-cmin-triad-1oct", name: "Arp C Minore (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "Cm", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["eb/4"], duration: "8", midiValue: 63 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["eb/4"], duration: "8", midiValue: 63 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ],
        notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["eb/3"], duration: "8", midiValue: 51 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["eb/3"], duration: "8", midiValue: 51 }, { keys: ["c/3"], duration: "q", midiValue: 48 } ]},

    // === Sezione 3: Arpeggi Settima (Asc/Desc 1 Ottava) ===
    { id: "arp-cmaj7-1oct", name: "Arp Cmaj7 (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["c/5"], duration: "q", midiValue: 72 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ],
        notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["c/3"], duration: "q", midiValue: 48 } ]},
    { id: "arp-am7-1oct", name: "Arp Am7 (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "Am", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["a/5"], duration: "q", midiValue: 81 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["a/4"], duration: "q", midiValue: 69 } ],
        notesBass: [ { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["a/3"], duration: "q", midiValue: 57 } ]},
    { id: "arp-g7-1oct", name: "Arp G7 (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["f/5"], duration: "8", midiValue: 77 }, { keys: ["g/5"], duration: "q", midiValue: 79 }, { keys: ["f/5"], duration: "8", midiValue: 77 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["g/4"], duration: "q", midiValue: 67 } ],
        notesBass: [ { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["g/3"], duration: "q", midiValue: 55 } ]},
    { id: "arp-fmaj7-1oct", name: "Arp Fmaj7 (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "F", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["f/5"], duration: "q", midiValue: 77 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["f/4"], duration: "q", midiValue: 65 } ],
        notesBass: [ { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["f/3"], duration: "q", midiValue: 53 } ]},
     { id: "arp-dm7-1oct", name: "Arp Dm7 (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "F", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["d/5"], duration: "q", midiValue: 74 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["d/4"], duration: "q", midiValue: 62 } ],
        notesBass: [ { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["d/3"], duration: "q", midiValue: 50 } ]},
     { id: "arp-e7-1oct", name: "Arp E7 (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "A", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g#/4"], duration: "8", midiValue: 68 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["e/5"], duration: "q", midiValue: 76 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["g#/4"], duration: "8", midiValue: 68 }, { keys: ["e/4"], duration: "q", midiValue: 64 } ],
        notesBass: [ { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g#/3"], duration: "8", midiValue: 56 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["g#/3"], duration: "8", midiValue: 56 }, { keys: ["e/3"], duration: "q", midiValue: 52 } ]},

    // === Sezione 4: Arpeggi Diminuiti e Aumentati ===
    { id: "arp-cdim7-1oct", name: "Arp Cdim7 (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["eb/4"], duration: "8", midiValue: 63 }, { keys: ["gb/4"], duration: "8", midiValue: 66 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c/5"], duration: "q", midiValue: 72 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["gb/4"], duration: "8", midiValue: 66 }, { keys: ["eb/4"], duration: "8", midiValue: 63 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ],
        notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["eb/3"], duration: "8", midiValue: 51 }, { keys: ["gb/3"], duration: "8", midiValue: 54 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["gb/3"], duration: "8", midiValue: 54 }, { keys: ["eb/3"], duration: "8", midiValue: 51 }, { keys: ["c/3"], duration: "q", midiValue: 48 } ]},
    { id: "arp-adim7-1oct", name: "Arp Adim7 (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["eb/5"], duration: "8", midiValue: 75 }, { keys: ["gb/5"], duration: "8", midiValue: 78 }, { keys: ["a/5"], duration: "q", midiValue: 81 }, { keys: ["gb/5"], duration: "8", midiValue: 78 }, { keys: ["eb/5"], duration: "8", midiValue: 75 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["a/4"], duration: "q", midiValue: 69 } ],
        notesBass: [ { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["eb/4"], duration: "8", midiValue: 63 }, { keys: ["gb/4"], duration: "8", midiValue: 66 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["gb/4"], duration: "8", midiValue: 66 }, { keys: ["eb/4"], duration: "8", midiValue: 63 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["a/3"], duration: "q", midiValue: 57 } ]},
    { id: "arp-caug-triad-1oct", name: "Arp C Aumentato (1 Ottava)", category: "arpeggi", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g#/4"], duration: "8", midiValue: 68 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["g#/4"], duration: "8", midiValue: 68 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ],
        notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g#/3"], duration: "8", midiValue: 56 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["g#/3"], duration: "8", midiValue: 56 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["c/3"], duration: "q", midiValue: 48 } ]},

    // === Sezione 5: Arpeggi con Pattern Ritmici Diversi ===
    { id: "arp-cmaj-triad-triplet", name: "Arp C Magg (Terzine - Crome)", category: "arpeggi", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ],
        notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["c/3"], duration: "q", midiValue: 48 } ]},
     { id: "arp-cmaj7-broken", name: "Arp Cmaj7 Spezzato Pattern 1", category: "arpeggi", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["c/5"], duration: "q", midiValue: 72 } ],
        notesBass: [ { keys: ["c/3"], duration: "w", midiValue: 48 }, { keys: ["c/3"], duration: "w", midiValue: 48 }, { keys: ["c/3"], duration: "w", midiValue: 48 } ]},
     { id: "arp-g7-broken-swing", name: "Arp G7 Spezzato (Swing 8ths)", category: "arpeggi", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5,
        // Swing non è rappresentato visualmente, ma il pattern è comune
        notesTreble: [ { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["f/5"], duration: "8", midiValue: 77 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["f/5"], duration: "8", midiValue: 77 }, { keys: ["g/5"], duration: "8", midiValue: 79 } ],
        notesBass: [ { keys: ["g/3"], duration: "q", midiValue: 55 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["g/3"], duration: "q", midiValue: 55 }, { keys: ["d/4"], duration: "q", midiValue: 62 } ]}, // Basso alternato semplice

    // === Sezione 6: Arpeggi su 2 Ottave (Mani Separate) ===
     { id: "arp-cmaj-triad-2oct-RH", name: "Arp C Magg (2 Ottave) RH", category: "arpeggi", staveLayout: "single", clef: "treble", keySignature: "C", timeSignature: "4/4", repetitions: 3,
        notes: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["c/6"], duration: "q", midiValue: 84 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ]},
    { id: "arp-cmaj-triad-2oct-LH", name: "Arp C Magg (2 Ottave) LH", category: "arpeggi", staveLayout: "single", clef: "bass", keySignature: "C", timeSignature: "4/4", repetitions: 3,
        notes: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["c/5"], duration: "q", midiValue: 72 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["c/3"], duration: "q", midiValue: 48 } ]},
     { id: "arp-amin-triad-2oct-RH", name: "Arp A Min (2 Ottave) RH", category: "arpeggi", staveLayout: "single", clef: "treble", keySignature: "Am", timeSignature: "4/4", repetitions: 3,
        notes: [ { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["a/5"], duration: "8", midiValue: 81 }, { keys: ["c/6"], duration: "8", midiValue: 84 }, { keys: ["e/6"], duration: "8", midiValue: 88 }, { keys: ["a/6"], duration: "q", midiValue: 93 }, { keys: ["e/6"], duration: "8", midiValue: 88 }, { keys: ["c/6"], duration: "8", midiValue: 84 }, { keys: ["a/5"], duration: "8", midiValue: 81 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["a/4"], duration: "q", midiValue: 69 } ]},
    { id: "arp-amin-triad-2oct-LH", name: "Arp A Min (2 Ottave) LH", category: "arpeggi", staveLayout: "single", clef: "bass", keySignature: "Am", timeSignature: "4/4", repetitions: 3,
        notes: [ { keys: ["a/2"], duration: "8", midiValue: 45 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["a/2"], duration: "q", midiValue: 45 } ]},
    { id: "arp-g7-2oct-RH", name: "Arp G7 (2 Ottave) RH", category: "arpeggi", staveLayout: "single", clef: "treble", keySignature: "C", timeSignature: "4/4", repetitions: 3,
        notes: [ { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["f/5"], duration: "8", midiValue: 77 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["b/5"], duration: "8", midiValue: 83 }, { keys: ["d/6"], duration: "8", midiValue: 86 }, { keys: ["f/6"], duration: "8", midiValue: 89 }, { keys: ["g/6"], duration: "q", midiValue: 91 }, { keys: ["f/6"], duration: "8", midiValue: 89 }, { keys: ["d/6"], duration: "8", midiValue: 86 }, { keys: ["b/5"], duration: "8", midiValue: 83 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["f/5"], duration: "8", midiValue: 77 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["g/4"], duration: "q", midiValue: 67 }]},
    { id: "arp-g7-2oct-LH", name: "Arp G7 (2 Ottave) LH", category: "arpeggi", staveLayout: "single", clef: "bass", keySignature: "C", timeSignature: "4/4", repetitions: 3,
        notes: [ { keys: ["g/2"], duration: "8", midiValue: 43 }, { keys: ["b/2"], duration: "8", midiValue: 47 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["b/2"], duration: "8", midiValue: 47 }, { keys: ["g/2"], duration: "q", midiValue: 43 }]},

]; // Fine array arpeggiExercises

// Rendi l'array accessibile globalmente
window.exerciseData = window.exerciseData || {};
window.exerciseData.arpeggi = arpeggiExercises; // Usa la chiave corretta

console.log("Dati Esercizi Arpeggi (Super Ampliati) Caricati.");