/**
 * js/exercises/licks_blues_ragtime.js
 * Brevi frasi e lick comuni nel linguaggio Blues e Ragtime.
 * **VERSIONE CORRETTA E AMPLIATA**
 */

const licksBluesRagtimeExercises = [

    // === Licks Blues (Ampliati) ===
    { id: "lick-blues-minor-pent-Am-1", name: "Lick Pent Min (Am) - Desc", category: "licks_blues_ragtime", clef: "treble", keySignature: "Am", timeSignature: "4/4", repetitions: 4, notes: [ { keys: ["a/5"], duration: "8", midiValue: 81 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["e/5"], duration: "q", midiValue: 76 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["a/4"], duration: "h", midiValue: 69 } ] },
    { id: "lick-blues-minor-pent-Am-2", name: "Lick Pent Min (Am) - Asc", category: "licks_blues_ragtime", clef: "treble", keySignature: "Am", timeSignature: "4/4", repetitions: 4, notes: [ { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["g/5"], duration: "q", midiValue: 79 }, { keys: ["a/5"], duration: "h", midiValue: 81 } ] },
    { id: "lick-blues-minor-pent-Em", name: "Lick Pent Min (Em)", category: "licks_blues_ragtime", clef: "treble", keySignature: "G", timeSignature: "4/4", repetitions: 4, notes: [ { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["g/4"], duration: "h", midiValue: 67 } ] },
    { id: "lick-blues-blue-note-C-1", name: "Lick Blue Note (C) - Eb", category: "licks_blues_ragtime", clef: "treble", keySignature: "F", timeSignature: "4/4", repetitions: 4, notes: [ { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["eb/4"], duration: "q", midiValue: 63 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["f#/4"], duration: "8", midiValue: 66 }, { keys: ["g/4"], duration: "h", midiValue: 67 } ] },
    { id: "lick-blues-blue-note-C-2", name: "Lick Blue Note (C) - Gb", category: "licks_blues_ragtime", clef: "treble", keySignature: "C", timeSignature: "4/4", repetitions: 4, notes: [ { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["gb/4"], duration: "q", midiValue: 66 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["e/4"], duration: "q", midiValue: 64 } ] },
    { id: "lick-blues-blue-note-G", name: "Lick Blue Note (G) - Bb", category: "licks_blues_ragtime", clef: "treble", keySignature: "C", timeSignature: "4/4", repetitions: 4, notes: [ { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["bb/4"], duration: "q", midiValue: 70 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["c#/5"], duration: "8", midiValue: 73 }, { keys: ["d/5"], duration: "h", midiValue: 74 } ] },
    { id: "lick-blues-turnaround-G", name: "Lick Turnaround Blues (G)", category: "licks_blues_ragtime", clef: "treble", keySignature: "C", timeSignature: "4/4", repetitions: 4, notes: [ { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["f/5"], duration: "8", midiValue: 77 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["f#/4"], duration: "8", midiValue: 66 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ] },
    { id: "lick-blues-turnaround-A", name: "Lick Turnaround Blues (A)", category: "licks_blues_ragtime", clef: "treble", keySignature: "D", timeSignature: "4/4", repetitions: 4, notes: [ // Su A7 D7 A7 E7
        { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["c#/5"], duration: "8", midiValue: 73 }, // A7
        { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["f#/5"], duration: "8", midiValue: 78 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, // D7
        { keys: ["c#/5"], duration: "8", midiValue: 73 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, // E7 -> A
        { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["a/3"], duration: "q", midiValue: 57 } // Risoluzione A
    ] },
    { id: "lick-blues-call-response-Am", name: "Lick Call & Response (Am)", category: "licks_blues_ragtime", clef: "treble", keySignature: "Am", timeSignature: "4/4", repetitions: 4, notes: [ { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["d/5"], duration: "q", midiValue: 74 }, { keys: ["r/4"], duration: "h"}, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["a/4"], duration: "h", midiValue: 69 } ] },
    { id: "lick-blues-slide-E", name: "Lick Blues Slide (E) - Sim.", category: "licks_blues_ragtime", clef: "treble", keySignature: "A", timeSignature: "4/4", repetitions: 4, notes: [ { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["g#/4"], duration: "q.", midiValue: 68 }, { keys: ["b/4"], duration: "h", midiValue: 71 } ] },
    { id: "lick-blues-double-stop-C", name: "Lick Blues Double Stop (C)", category: "licks_blues_ragtime", clef: "treble", keySignature: "F", timeSignature: "4/4", repetitions: 4, notes: [ { keys: ["c/4", "eb/4"], duration: "q", midiValues: [60, 63] }, { keys: ["d/4", "f/4"], duration: "q", midiValues: [62, 65] }, { keys: ["c/4", "eb/4"], duration: "h", midiValues: [60, 63] } ]},
    { id: "lick-blues-boogie-LH", name: "Pattern Boogie Woogie Base (LH)", category: "licks_blues_ragtime", clef: "bass", keySignature: "C", timeSignature: "4/4", repetitions: 4,
      notes: [ // C C E G | F F A C | C C E G | G G B D ...
          { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["c/4"], duration: "8", midiValue: 60 },
          { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["d/4"], duration: "8", midiValue: 62 }
      ] },

    // === Pattern Ragtime Semplificati (Mantenuti e Ampliati) ===
    { id: "lick-ragtime-stride-LH-C", name: "Pattern Ragtime Stride Base (LH - C)", category: "licks_blues_ragtime", clef: "bass", keySignature: "C", timeSignature: "2/4", repetitions: 5, notes: [ { keys: ["c/2"], duration: "8", midiValue: 36 }, { keys: ["c/3", "e/3", "g/3"], duration: "8", midiValues: [48, 52, 55] }, { keys: ["c/2"], duration: "8", midiValue: 36 }, { keys: ["c/3", "e/3", "g/3"], duration: "8", midiValues: [48, 52, 55] } ] },
    { id: "lick-ragtime-stride-LH-G7", name: "Pattern Ragtime Stride Base (LH - G7)", category: "licks_blues_ragtime", clef: "bass", keySignature: "C", timeSignature: "2/4", repetitions: 5, notes: [ { keys: ["g/2"], duration: "8", midiValue: 43 }, { keys: ["b/2", "d/3", "f/3"], duration: "8", midiValues: [47, 50, 53] }, { keys: ["g/2"], duration: "8", midiValue: 43 }, { keys: ["b/2", "d/3", "f/3"], duration: "8", midiValues: [47, 50, 53] } ] },
    { id: "lick-ragtime-stride-LH-F", name: "Pattern Ragtime Stride Base (LH - F)", category: "licks_blues_ragtime", clef: "bass", keySignature: "C", timeSignature: "2/4", repetitions: 5, notes: [ { keys: ["f/2"], duration: "8", midiValue: 41 }, { keys: ["a/2", "c/3", "f/3"], duration: "8", midiValues: [45, 48, 53] }, { keys: ["f/2"], duration: "8", midiValue: 41 }, { keys: ["a/2", "c/3", "f/3"], duration: "8", midiValues: [45, 48, 53] } ] },
    { id: "lick-ragtime-stride-LH-Am", name: "Pattern Ragtime Stride Base (LH - Am)", category: "licks_blues_ragtime", clef: "bass", keySignature: "C", timeSignature: "2/4", repetitions: 5, notes: [ { keys: ["a/2"], duration: "8", midiValue: 45 }, { keys: ["a/3", "c/4", "e/4"], duration: "8", midiValues: [57, 60, 64] }, { keys: ["a/2"], duration: "8", midiValue: 45 }, { keys: ["a/3", "c/4", "e/4"], duration: "8", midiValues: [57, 60, 64] } ] },
    { id: "lick-ragtime-sync-RH-1", name: "Pattern Ragtime Melodia Sincopata 1 (RH)", category: "licks_blues_ragtime", clef: "treble", keySignature: "C", timeSignature: "2/4", repetitions: 5, notes: [ { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["g/4"], duration: "8", midiValue: 67 } ] },
    { id: "lick-ragtime-sync-RH-2", name: "Pattern Ragtime Melodia Sincopata 2 (RH)", category: "licks_blues_ragtime", clef: "treble", keySignature: "C", timeSignature: "2/4", repetitions: 5, notes: [ { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["e/4"], duration: "8", midiValue: 64 } ] },
    { id: "lick-ragtime-sync-RH-3", name: "Pattern Ragtime Melodia Sincopata 3 (RH)", category: "licks_blues_ragtime", clef: "treble", keySignature: "C", timeSignature: "4/4", repetitions: 5, notes: [ { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["g/4"], duration: "q", midiValue: 67 } ] },
    { id: "lick-ragtime-octave-RH", name: "Pattern Ragtime Melodia in Ottave (RH)", category: "licks_blues_ragtime", clef: "treble", keySignature: "C", timeSignature: "4/4", repetitions: 5, notes: [ { keys: ["c/4", "c/5"], duration: "q", midiValues: [60, 72] }, { keys: ["d/4", "d/5"], duration: "q", midiValues: [62, 74] }, { keys: ["e/4", "e/5"], duration: "h", midiValues: [64, 76] } ] },
    { id: "lick-ragtime-chrom-desc", name: "Pattern Ragtime Discesa Cromatica", category: "licks_blues_ragtime", clef: "treble", keySignature: "C", timeSignature: "4/4", repetitions: 5, notes: [ { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["eb/5"], duration: "8", midiValue: 75 }, { keys: ["d/5"], duration: "8", midiValue: 74 }, { keys: ["db/5"], duration: "8", midiValue: 73 }, { keys: ["c/5"], duration: "q", midiValue: 72 }, { keys: ["b/4"], duration: "q", midiValue: 71 } ] },
    { id: "lick-ragtime-jump-LH", name: "Pattern Ragtime Salto Basso (LH)", category: "licks_blues_ragtime", clef: "bass", keySignature: "C", timeSignature: "2/4", repetitions: 5, notes: [ { keys: ["c/2"], duration: "8", midiValue: 36 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["g/2"], duration: "8", midiValue: 43 }, { keys: ["c/3"], duration: "8", midiValue: 48 } ] },


];
window.exerciseData = window.exerciseData || {};
// Aggiungi o sovrascrivi questa categoria specifica
window.exerciseData.licks_blues_ragtime = licksBluesRagtimeExercises;
console.log("Dati Esercizi Licks Blues/Ragtime (Ampliati e Corretti) Caricati.");