/**
 * js/exercises/tecnica_coordinazione.js
 * Esercizi per migliorare la tecnica pianistica e la coordinazione tra le mani.
 * **VERSIONE SUPER AMPLIATA**
 */

const tecnicaCoordinazioneExercises = [

    // === Sezione 1: Ritmi Diversi ===
    { id: "indep-01-rhQ-lh8", name: "Ritmo 1: RH Q / LH 8 (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["g/4"], duration: "w", midiValue: 67 } ], notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["c/3"], duration: "w", midiValue: 48 } ] },
    { id: "indep-02-rh8-lhQ", name: "Ritmo 2: RH 8 / LH Q (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["c/4"], duration: "w", midiValue: 60 } ], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["d/3"], duration: "q", midiValue: 50 }, { keys: ["e/3"], duration: "q", midiValue: 52 }, { keys: ["f/3"], duration: "q", midiValue: 53 }, { keys: ["g/3"], duration: "w", midiValue: 55 } ] },
    { id: "indep-03-rhHold-lhMove", name: "Ritmo 3: RH Tiene / LH 8 (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "w", midiValue: 60 }, { keys: ["c/4"], duration: "w", midiValue: 60 } ], notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["d/3"], duration: "8", midiValue: 50 } ] },
    { id: "indep-04-lhHold-rhMove", name: "Ritmo 4: LH Tiene / RH 8 (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["d/4"], duration: "8", midiValue: 62 } ], notesBass: [ { keys: ["c/3"], duration: "w", midiValue: 48 }, { keys: ["c/3"], duration: "w", midiValue: 48 } ] },
    { id: "indep-05-rhDotted-lhQ", name: "Ritmo 5: RH Puntato / LH Q (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "8d", midiValue: 60 }, { keys: ["d/4"], duration: "16", midiValue: 62 }, { keys: ["e/4"], duration: "8d", midiValue: 64 }, { keys: ["f/4"], duration: "16", midiValue: 65 }, { keys: ["g/4"], duration: "8d", midiValue: 67 }, { keys: ["f/4"], duration: "16", midiValue: 65 }, { keys: ["e/4"], duration: "8d", midiValue: 64 }, { keys: ["d/4"], duration: "16", midiValue: 62 }, { keys: ["c/4"], duration: "h", midiValue: 60 } ], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["d/3"], duration: "q", midiValue: 50 }, { keys: ["e/3"], duration: "q", midiValue: 52 }, { keys: ["f/3"], duration: "q", midiValue: 53 }, { keys: ["g/3"], duration: "h", midiValue: 55 } ] },
    { id: "indep-06-lhDotted-rhQ", name: "Ritmo 6: LH Puntato / RH Q (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["g/4"], duration: "h", midiValue: 67 } ], notesBass: [ { keys: ["c/3"], duration: "8d", midiValue: 48 }, { keys: ["d/3"], duration: "16", midiValue: 50 }, { keys: ["e/3"], duration: "8d", midiValue: 52 }, { keys: ["f/3"], duration: "16", midiValue: 53 }, { keys: ["g/3"], duration: "8d", midiValue: 55 }, { keys: ["f/3"], duration: "16", midiValue: 53 }, { keys: ["e/3"], duration: "8d", midiValue: 52 }, { keys: ["d/3"], duration: "16", midiValue: 50 }, { keys: ["c/3"], duration: "h", midiValue: 48 } ] },
    { id: "indep-07-rhTriplet-lhQ", name: "Ritmo 7: RH Terzine 8 / LH Q (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["d/4"], duration: "8", midiValue: 62 },{ keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["d/4"], duration: "8", midiValue: 62 },{ keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 },{ keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["f/4"], duration: "8", midiValue: 65 },{ keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["g/4"], duration: "h", midiValue: 67 }], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["d/3"], duration: "q", midiValue: 50 }, { keys: ["e/3"], duration: "q", midiValue: 52 }, { keys: ["f/3"], duration: "q", midiValue: 53 }, { keys: ["g/3"], duration: "h", midiValue: 55 }] },
    { id: "indep-08-lhTriplet-rhQ", name: "Ritmo 8: LH Terzine 8 / RH Q (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["g/4"], duration: "h", midiValue: 67 } ], notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["d/3"], duration: "8", midiValue: 50 },{ keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["d/3"], duration: "8", midiValue: 50 },{ keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["f/3"], duration: "8", midiValue: 53 },{ keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["f/3"], duration: "8", midiValue: 53 },{ keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["g/3"], duration: "h", midiValue: 55 } ] },

    // === Sezione 2: Moto Contrario ===
    { id: "indep-09-contrary-scale-Cmaj", name: "Contrario 1: Scala Do Magg", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["b/4"], duration: "q", midiValue: 71 }, { keys: ["c/5"], duration: "q", midiValue: 72 } ], notesBass: [ { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["b/3"], duration: "q", midiValue: 59 }, { keys: ["a/3"], duration: "q", midiValue: 57 }, { keys: ["g/3"], duration: "q", midiValue: 55 }, { keys: ["f/3"], duration: "q", midiValue: 53 }, { keys: ["e/3"], duration: "q", midiValue: 52 }, { keys: ["d/3"], duration: "q", midiValue: 50 }, { keys: ["c/3"], duration: "q", midiValue: 48 } ] },
    { id: "indep-10-contrary-scale-Gmaj", name: "Contrario 2: Scala Sol Magg", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "G", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["b/4"], duration: "q", midiValue: 71 }, { keys: ["c/5"], duration: "q", midiValue: 72 }, { keys: ["d/5"], duration: "q", midiValue: 74 }, { keys: ["e/5"], duration: "q", midiValue: 76 }, { keys: ["f#/5"], duration: "q", midiValue: 78 }, { keys: ["g/5"], duration: "q", midiValue: 79 } ], notesBass: [ { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["f#/4"], duration: "q", midiValue: 66 }, { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["b/3"], duration: "q", midiValue: 59 }, { keys: ["a/3"], duration: "q", midiValue: 57 }, { keys: ["g/3"], duration: "q", midiValue: 55 } ] },
    { id: "indep-11-contrary-scale-AminHarm", name: "Contrario 3: Scala La Min Arm", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "Am", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["b/4"], duration: "q", midiValue: 71 }, { keys: ["c/5"], duration: "q", midiValue: 72 }, { keys: ["d/5"], duration: "q", midiValue: 74 }, { keys: ["e/5"], duration: "q", midiValue: 76 }, { keys: ["f/5"], duration: "q", midiValue: 77 }, { keys: ["g#/5"], duration: "q", midiValue: 80 }, { keys: ["a/5"], duration: "q", midiValue: 81 } ], notesBass: [ { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["g#/4"], duration: "q", midiValue: 68 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["b/3"], duration: "q", midiValue: 59 }, { keys: ["a/3"], duration: "q", midiValue: 57 } ] },
    { id: "indep-12-contrary-arpeggio-Cmaj", name: "Contrario 4: Arpeggio Do Magg", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["e/5"], duration: "8", midiValue: 76 }, { keys: ["g/5"], duration: "8", midiValue: 79 }, { keys: ["c/6"], duration: "q", midiValue: 84 }], notesBass: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["g/2"], duration: "8", midiValue: 43 }, { keys: ["e/2"], duration: "8", midiValue: 40 }, { keys: ["c/2"], duration: "q", midiValue: 36 } ] },
    { id: "indep-13-contrary-chromatic-C", name: "Contrario 5: Cromatica da Do (8 note)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["c#/4"], duration: "8", midiValue: 61 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["d#/4"], duration: "8", midiValue: 63 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["f#/4"], duration: "8", midiValue: 66 }, { keys: ["g/4"], duration: "q", midiValue: 67 } ], notesBass: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["bb/3"], duration: "8", midiValue: 58 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["ab/3"], duration: "8", midiValue: 56 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["gb/3"], duration: "8", midiValue: 54 }, { keys: ["f/3"], duration: "q", midiValue: 53 } ] },

    // === Sezione 3: Moto Parallelo a Intervalli Diversi ===
    { id: "indep-14-parallel-3rds-Cmaj", name: "Parallelo 1: Terze (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["b/4"], duration: "h", midiValue: 71 } ], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["d/3"], duration: "q", midiValue: 50 }, { keys: ["e/3"], duration: "q", midiValue: 52 }, { keys: ["f/3"], duration: "q", midiValue: 53 }, { keys: ["g/3"], duration: "h", midiValue: 55 } ] },
    { id: "indep-15-parallel-6ths-Cmaj", name: "Parallelo 2: Seste (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["b/4"], duration: "q", midiValue: 71 }, { keys: ["c/5"], duration: "q", midiValue: 72 }, { keys: ["d/5"], duration: "q", midiValue: 74 }, { keys: ["e/5"], duration: "h", midiValue: 76 } ], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["d/3"], duration: "q", midiValue: 50 }, { keys: ["e/3"], duration: "q", midiValue: 52 }, { keys: ["f/3"], duration: "q", midiValue: 53 }, { keys: ["g/3"], duration: "h", midiValue: 55 } ] },
    { id: "indep-16-parallel-3rds-Gmaj", name: "Parallelo 3: Terze (Sol Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "G", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["b/4"], duration: "q", midiValue: 71 }, { keys: ["c/5"], duration: "q", midiValue: 72 }, { keys: ["d/5"], duration: "q", midiValue: 74 }, { keys: ["e/5"], duration: "q", midiValue: 76 }, { keys: ["f#/5"], duration: "h", midiValue: 78 } ], notesBass: [ { keys: ["g/3"], duration: "q", midiValue: 55 }, { keys: ["a/3"], duration: "q", midiValue: 57 }, { keys: ["b/3"], duration: "q", midiValue: 59 }, { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["d/4"], duration: "h", midiValue: 62 } ] },
    { id: "indep-17-parallel-6ths-Amin", name: "Parallelo 4: Seste (La Min Nat)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "Am", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["f/5"], duration: "q", midiValue: 77 }, { keys: ["g/5"], duration: "q", midiValue: 79 }, { keys: ["a/5"], duration: "q", midiValue: 81 }, { keys: ["b/5"], duration: "q", midiValue: 83 }, { keys: ["c/6"], duration: "h", midiValue: 84 } ], notesBass: [ { keys: ["a/3"], duration: "q", midiValue: 57 }, { keys: ["b/3"], duration: "q", midiValue: 59 }, { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["e/4"], duration: "h", midiValue: 64 } ] },
    { id: "indep-18-parallel-4ths-Cmaj", name: "Parallelo 5: Quarte (Do Magg)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["b/4"], duration: "q", midiValue: 71 }, { keys: ["c/5"], duration: "h", midiValue: 72 } ], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["d/3"], duration: "q", midiValue: 50 }, { keys: ["e/3"], duration: "q", midiValue: 52 }, { keys: ["f/3"], duration: "q", midiValue: 53 }, { keys: ["g/3"], duration: "h", midiValue: 55 } ] },

    // === Sezione 4: Ostinato vs Melodia/Scala ===
    { id: "indep-19-ostinatoLH-scaleRH-Cmaj", name: "Ostinato 1: LH C-G / RH Scala Do", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["b/4"], duration: "q", midiValue: 71 }, { keys: ["c/5"], duration: "q", midiValue: 72 } ], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["g/3"], duration: "q", midiValue: 55 }, { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["g/3"], duration: "q", midiValue: 55 }, { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["g/3"], duration: "q", midiValue: 55 }, { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["g/3"], duration: "q", midiValue: 55 } ] },
    { id: "indep-20-ostinatoRH-scaleLH-Cmaj", name: "Ostinato 2: RH C-G / LH Scala Do", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["g/4"], duration: "q", midiValue: 67 } ], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["d/3"], duration: "q", midiValue: 50 }, { keys: ["e/3"], duration: "q", midiValue: 52 }, { keys: ["f/3"], duration: "q", midiValue: 53 }, { keys: ["g/3"], duration: "q", midiValue: 55 }, { keys: ["a/3"], duration: "q", midiValue: 57 }, { keys: ["b/3"], duration: "q", midiValue: 59 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ] },
    { id: "indep-21-ostinatoLH-arpeggioRH-Cmaj", name: "Ostinato 3: LH C-G / RH Arp Do", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["c/5"], duration: "8", midiValue: 72 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["g/3"], duration: "q", midiValue: 55 }, { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["g/3"], duration: "q", midiValue: 55 } ] },
    { id: "indep-22-ostinatoRH-arpeggioLH-Amin", name: "Ostinato 4: RH A-E / LH Arp La Min", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "Am", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["e/5"], duration: "q", midiValue: 76 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["e/5"], duration: "q", midiValue: 76 } ], notesBass: [ { keys: ["a/2"], duration: "8", midiValue: 45 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["a/2"], duration: "q", midiValue: 45 } ] },
    { id: "indep-23-ostinatoBrokenChordLH-melodyRH", name: "Ostinato 5: LH Arp Spezzato / RH Melodia", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5,
        notesTreble: [ { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["a/4"], duration: "q", midiValue: 69 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["f/4"], duration: "q", midiValue: 65 }, { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["c/4"], duration: "h", midiValue: 60 } ],
        notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["c/3"], duration: "w", midiValue: 48} ] // Termina su C
    },

    // --- Sezione 5: Sincopi e Ritmi Incrociati Semplici ---
    { id: "indep-24-sync-RHoffbeat", name: "Sincopi 1: RH Offbeat / LH Onbeat (Do)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["r/4"], duration: "8" }, { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["r/4"], duration: "8" }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["r/4"], duration: "8" }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["r/4"], duration: "8" }, { keys: ["f/4"], duration: "8", midiValue: 65 } ], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["d/3"], duration: "q", midiValue: 50 }, { keys: ["e/3"], duration: "q", midiValue: 52 }, { keys: ["f/3"], duration: "q", midiValue: 53 } ] },
    { id: "indep-25-sync-LHoffbeat", name: "Sincopi 2: LH Offbeat / RH Onbeat (Do)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "4/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["e/4"], duration: "q", midiValue: 64 }, { keys: ["f/4"], duration: "q", midiValue: 65 } ], notesBass: [ { keys: ["r/4"], duration: "8" }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["r/4"], duration: "8" }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["r/4"], duration: "8" }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["r/4"], duration: "8" }, { keys: ["f/3"], duration: "8", midiValue: 53 } ] },
    { id: "indep-26-polyrhythm-3over2-RH", name: "Ritmo Incrociato 1: RH 3 / LH 2 (3/4)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "3/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["a/4"], duration: "8", midiValue: 69 } ], notesBass: [ { keys: ["c/3"], duration: "q", midiValue: 48 }, { keys: ["g/3"], duration: "q", midiValue: 55 }, { keys: ["c/3"], duration: "q", midiValue: 48 } ] },
    { id: "indep-27-polyrhythm-3over2-LH", name: "Ritmo Incrociato 2: LH 3 / RH 2 (3/4)", category: "tecnica_coordinazione", staveLayout: "grand", keySignature: "C", timeSignature: "3/4", repetitions: 5, notesTreble: [ { keys: ["c/4"], duration: "q", midiValue: 60 }, { keys: ["g/4"], duration: "q", midiValue: 67 }, { keys: ["c/4"], duration: "q", midiValue: 60 } ], notesBass: [ { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["a/3"], duration: "8", midiValue: 57 } ] },

    // === Sezione 6: Hanon Semplificato e Agilità ===
    { id: "indep-28-hanon-like-12345", name: "Agilità 1: Hanon-like 1-2-3-4-5 (RH)", category: "tecnica_coordinazione", staveLayout: "single", clef:"treble", keySignature: "C", timeSignature: "4/4", repetitions: 5,
      notes: [ // C D E F G F E D | D E F G A G F E | ...
            { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["d/4"], duration: "8", midiValue: 62 },
            { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["e/4"], duration: "8", midiValue: 64 },
            { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["f/4"], duration: "8", midiValue: 65 },
            { keys: ["d/4"], duration: "q", midiValue: 62 }, { keys: ["c/4"], duration: "h", midiValue: 60 } // Semplice fine
      ]
    },
    { id: "indep-29-hanon-like-12345-LH", name: "Agilità 2: Hanon-like 1-2-3-4-5 (LH)", category: "tecnica_coordinazione", staveLayout: "single", clef:"bass", keySignature: "C", timeSignature: "4/4", repetitions: 5,
      notes: [ // C D E F G F E D | D E F G A G F E | ... (un ottava sotto)
            { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["d/3"], duration: "8", midiValue: 50 },
            { keys: ["d/3"], duration: "8", midiValue: 50 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["e/3"], duration: "8", midiValue: 52 },
            { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["b/3"], duration: "8", midiValue: 59 }, { keys: ["a/3"], duration: "8", midiValue: 57 }, { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["f/3"], duration: "8", midiValue: 53 },
            { keys: ["d/3"], duration: "q", midiValue: 50 }, { keys: ["c/3"], duration: "h", midiValue: 48 }
      ]
    },
     { id: "indep-30-hanon-thumb-under-RH", name: "Agilità 3: Passaggio Pollice Hanon (RH)", category: "tecnica_coordinazione", staveLayout: "single", clef:"treble", keySignature: "C", timeSignature: "4/4", repetitions: 5,
      notes: [ // C D E F | G A B C5 | B A G F | E D C B3 ... (semplificato)
            { keys: ["c/4"], duration: "8", midiValue: 60 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["f/4"], duration: "8", midiValue: 65 },
            { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["c/5"], duration: "8", midiValue: 72 },
            { keys: ["b/4"], duration: "8", midiValue: 71 }, { keys: ["a/4"], duration: "8", midiValue: 69 }, { keys: ["g/4"], duration: "8", midiValue: 67 }, { keys: ["f/4"], duration: "8", midiValue: 65 },
            { keys: ["e/4"], duration: "8", midiValue: 64 }, { keys: ["d/4"], duration: "8", midiValue: 62 }, { keys: ["c/4"], duration: "q", midiValue: 60 }
      ]
    },
     { id: "indep-31-hanon-thumb-under-LH", name: "Agilità 4: Passaggio Pollice Hanon (LH)", category: "tecnica_coordinazione", staveLayout: "single", clef:"bass", keySignature: "C", timeSignature: "4/4", repetitions: 5,
      notes: [ // G F E D | C B2 A2 G2 | A2 B2 C D | E F G A ... (semplificato)
            { keys: ["g/3"], duration: "8", midiValue: 55 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["d/3"], duration: "8", midiValue: 50 },
            { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["b/2"], duration: "8", midiValue: 47 }, { keys: ["a/2"], duration: "8", midiValue: 45 }, { keys: ["g/2"], duration: "8", midiValue: 43 },
            { keys: ["a/2"], duration: "8", midiValue: 45 }, { keys: ["b/2"], duration: "8", midiValue: 47 }, { keys: ["c/3"], duration: "8", midiValue: 48 }, { keys: ["d/3"], duration: "8", midiValue: 50 },
            { keys: ["e/3"], duration: "8", midiValue: 52 }, { keys: ["f/3"], duration: "8", midiValue: 53 }, { keys: ["g/3"], duration: "q", midiValue: 55 }
      ]
    },


]; // Fine array tecnicaCoordinazioneExercises

// Rendi l'array accessibile globalmente
window.exerciseData = window.exerciseData || {};
window.exerciseData.tecnica_coordinazione = tecnicaCoordinazioneExercises;

console.log("Dati Esercizi Tecnica e Coordinazione (Ampliati) Caricati.");